Csv export, last field in each row changed ';' for PHP_EOL.
revosystems/reporter pull request #3
Opened 2021-12-29 08:29 UTC by aleixgil

2021-12-29 08:44 UTC, PauBenetPrat commented on src/Exporters/CsvExporter.php
> +            $this->output .= $field->getTitle() . ($index == $exportFields->keys()->last() ? PHP_EOL : ';');
NOT BAD, fes un === no?

2022-01-05 11:19 UTC, aleixgil commented on src/Exporters/CsvExporter.php
> +            $this->output .= $field->getTitle() . ($index == $exportFields->keys()->last() ? PHP_EOL : ';');
@BadChoice pots revisar pls?

2022-01-06 14:21 UTC, BadChoice requested changes

2022-01-06 14:21 UTC, BadChoice commented on src/Exporters/CsvExporter.php
> +        foreach ($exportFields = $this->getExportFields() as $index => $field) {
no seria millor fer un map i un implode i llavors afegir el PHP_EOL?

2022-01-07 10:13 UTC, aleixgil commented on src/Exporters/CsvExporter.php
> +        foreach ($exportFields = $this->getExportFields() as $index => $field) {
@BadChoice corretgit aqui: https://github.com/revosystems/reporter/pull/4, contra una branca copia de master amb php7.

2022-01-07 10:13 UTC, closed without merging